# Diseños experimentales y cuasi-experimentales - Otoño 2024

Profesor magistrales: **Ignacio Spiousas** [ispiousas\@udesa.edu.ar](mailto:ispiousas@udesa.edu.ar)\
Profesor tutoriales: **Francisco Gallo** [frgallo\@itba.edu.ar](mailto:frgallo@itba.edu.ar)

## Objetivos de aprendizaje

El objetivo del curso es que los/as estudiantes sean capaces de diseñar experimentos para expresar y verificar efectivamente hipótesis científicas. Asimismo se busca generar intuiciones que les permitan evaluar diseños experimentales con los que se puedan encontrar tanto en la literatura científica como en cualquier dato obtenido experimentalmente que se les presente al momento de tomar una decisión.

Se espera que los estudiantes sean capaces de comunicar los diseños experimentales, sus resultados y las implicancias de los mismos de manera clara, concisa y "apta para todo público". Asímismo, Una parte importante de la materia es que los estudiantes incorporen la intuición de que no siempre es posible implementar un diseño experimental "ideal" (si este existiera) y que tomar decisiones informadas sobre los mismos (modelos estadísticos, métricas, diseños, etc.) es una parte importante de su formación.

El programa se estructura como una continuación del eje de estadística presentando aplicaciones experimentales a las ciencias del comportamiento y la cognición.

## Contenidos

En las clases se desarrollarán los conceptos teóricos y fundamentos científicos del diseño experimental y cuasi experimental en cuatro unidades básicas: Estadística aplicada a las ciencias del comportamiento, diseño experimental, diseño cuasi experimental y aplicaciones y reflexiones finales.

## Modalidad de trabajo

La modalidad de cursada será presencial. Se dictarán clases magistrales de dos horas cátedra por semana, acompañadas de una clase tutorial de una hora cátedra semanal. Los/as estudiantes solo podrán acumular un 25% de inasistencias por cualquier causa, y podrán faltar hasta un máximo de 4 clases. La asistencia virtual de manera sincrónica no se computa como asistencia, ya que la modalidad de la materia es presencial. Quienes por razones extraordinarias (por ejemplo, una enfermedad extensa) se vean forzados a superar ese límite, deberán solicitar a la Oficina de Alumnos ([alumnos\@udesa.edu.ar](mailto:alumnos@udesa.edu.ar)) la justificación de las faltas que correspondan, presentando la documentación que se les solicite.

En las clases magistrales se trabajará con exposiciones orales acompañadas por presentaciones, videos breves y presentaciones de bibliografía científica y código computacional, así como debates grupales.

Los recursos de la materia (presentaciones, bibliografía, guías de lectura, código computacional, consignas de actividades prácticas, etc.) serán publicados en el [Campus Virtual](http://campusvirtual.udesa.edu.ar/).

En las clases tutoriales se acompañará a los alumnos en la resolución de los trabajos prácticos propuestos por la cátedra. También se les brindará guía y seguimiento en el desarrollo del trabajo de medio término y el trabajo final.

Además de las clases tutoriales, los alumnos dispondrán de horarios de consulta semanales, cuyos turnos deberán solicitarse al finalizar la clase o por correo electrónico. El docente pactará con cada alumno el día y horario del encuentro, así como su modalidad (virtual o presencial).

## Mecanismo de evaluación

A lo largo de las clases magistrales y tutoriales se realizarán breves cuestionarios a fin de comprobar el seguimiento por parte de las/los estudiantes. Los mismos consistirán en dos o tres preguntas simples de tipo "multiple choice" que permitirá a docentes y estudiantes evaluar la correcta apropiación de los conceptos discutidos en el aula así como reforzar conceptos que no hayan quedado totalmente claros.

Se tomarán dos exámenes parciales. Los mismos serán escritos e individuales. Ambos exámenes serán presenciales y constarán de preguntas a desarrollar sobre los temas abordadosde la materia. Una condición necesaria para aprobar la materia es tener aprobados los dos exámenes parciales con un mínimo de 4 (cuatro). Para obtener la nota 4 (cuatro) será necesario responder correctamente el 50% de las consignas. Es posible recuperar ambos exámenes parciales.

Asimismo, los/las estudiantes deberán realizar dos trabajos grupales a lo largo del curso que también serán evaluados numéricamente y deberán ser aprobados con un mínimo de 4 (cuatro):

a)  **Trabajo de medio término:** Diseño de un experimento para verificar una hipótesis relacionada con las ciencias del comportamiento. La cátedra ofrecerá una lista de hipótesis (con sus respectivos contextos y antecedentes) y los grupos de estudiantes deberán diseñar un experimento que verifique la hipótesis elegida de forma eficiente. Deberán justificar sus elecciones en base a los contenidos de la materia. Finalmente, cada grupo debera presentar un informe y exponer oralmente los resultados obtenidos.

b)  **Trabajo final:** Diseño e implementación de un cuasi experimento utilizando datos abiertos. Se le propondrá a los estudiantes una serie de bases de datos abiertos (por ejemplo, https://datos.gob.ar/) a partir de la cual cada grupo deberá proponer una hipótesis relacionada con las ciencias del comportamiento. Luego, deberán diseñar un experimento para verificarla y llevar adelante el cuasi experimento. Finalmente, cada grupo debera presentar un informe y exponer oralmente los resultados obtenidos.

Los grupos serán integrados al comienzo de la cursada por un máximo de 3 estudiantes y el desarrollo de estos trabajos será seguido en el marco de las clases tutoriales.

La nota final corresponderá a un promedio ponderado de las cinco instancias de evaluación:

::: callout-note
**Nota final = 0.35 \* Primer examen parcial + 0.35 \* Segundo examen parcial + 0.15 \* Trabajo de medio término + 0.15 \* Trabajo final**
:::

Se requerirá una nota final de al menos 4 (cuatro) puntos para aprobar la materia.

## Descripción de actividades tutoriales

En la primera parte de los tutoriales se trabajará en reforzar la base computacional y estadística para que los estudiantes se sientan seguros al momento de incorporar las nuevas herramientas y desarrollar los trabajos prácticos que se presentan como obligatorios (TP 1 a 3 en el programa).

Luego, los tutoriales se concentrarán especificamente en guiar a los estudiantes en el desarrollo del trabajo práctico de medio término (diseño experimental) y el trabajo final de la materia (diseño cuasi experimental). Los contenidos presentados en estos tutoriales complementarán al contenido de las clases magistrales cerrando la brecha entre la presentación teórica de los conceptos y sus usos prácticos en ejemplos concretos de la práctica real de ciencias del comportamiento.

## Plagio y deshonestidad intelectual

La Universidad de San Andrés exige un estricto apego a los cánones de honestidad intelectual. La existencia de plagio constituye un grave deshonor, impropio de la vida universitaria. Su configuración no sólo se produce con la existencia de copia literal en los exámenes o presentaciones, sino toda vez que se advierta un aprovechamiento abusivo del esfuerzo intelectual ajeno. El [Código de Ética](https://www.udesa.edu.ar/sites/default/files/bluebook2020.pdf) considera conducta punible la apropiación de la labor intelectual ajena, por lo que se recomienda apegarse a los formatos académicos generalmente aceptados (MLA, APA, Chicago, etc.) para las citas y referencias bibliográficas (incluyendo los formatos en línea). En caso de dudas recomendamos consultar el sitio: www.udesa.edu.ar/biblioteca/plagio. La violación de estas normas dará lugar a sanciones académicas y disciplinarias que pueden ir desde el apercibimiento hasta la expulsión de la Universidad.

## Bibliografía general de la materia

@herzog2019understanding y @reichardt2019quasi

## Unidad 1: Estadística aplicada a las ciencias del comportamiento

### Semana 1: Objetivos y organización de la materia. Introducción a la recolección y análisis de datos.

**Clase magistral:** Cronograma y presentación de la organización de la materia. Presentación de los trabajos de medio término y final y del plantel docente. Motivación: ¿Para qué sirve el diseño experimental? ¿Cuál es la diferencia entre diseño experimental y cuasi experimental? Conceptos básicos de probabilidad. Presentación de las herramientas computacionales del curso: R y el tidyverse (dplyt, ggplot2, readr, tidyr, etc.).

**Bibliografía:** Herzog, M. H., Francis, G., & Clarke, A. (2019). Understanding statistics and experimental design: how to not lie with statistics (chap. 2). Springer Nature. Wickham, H., Averick, M., Bryan, J., Chang, W., McGowan, L. D. A., François, R., ... & Yutani, H. (2019). Welcome to the Tidyverse. Journal of open source software, 4(43), 1686. Clase tutorial: Las clases tutoriales comienzan la semana 2.

### Semana 2: Probabilidad y estadística, las dos caras de una misma moneda

**Clase magistral:** Concepto de población y muestra. Tipos de variables y su intrumentalización El concepto de estimación como el puente entre la muestra y la población, reinterpretación del concepto de inferencia estadística en este contexto. Covarianza y correlación. Diseño experimental y conceptos básicos de estadística: Teoría de detección de la señal (SDT). El d' empírico.

**Clase tutorial:** Repaso de R. Clase de repaso del uso de R para el análisis de datos. Presentación de funciones básicas de tidyverse y ggplot2. Resolución del TP1 (Introducción a dplyr y ggplot2).

Bibliografía: Herzog, M. H., Francis, G., & Clarke, A. (2019). Understanding statistics and experimental design: how to not lie with statistics (chap. 2 and 3). Springer Nature. Wickham, H., Averick, M., Bryan, J., Chang, W., McGowan, L. D. A., François, R., ... & Yutani, H. (2019). Welcome to the Tidyverse. Journal of open source software, 4(43), 1686. Unidad 2: Diseño experimental

Semana 3

Clase magistral: Introducción a los conceptos básicos del diseño experimental. Tipos de diseños experimentales (bloques, contrabalanceo, etc.). Aleateorización.

Temas: Presentación de los conceptos básicos del diseño experimental. Diseños de bloques y diseños factoriales, ventajas y desventajas. Diseños de bloque en experimentos de neuroimagentes (fMRI y EEG). Contrabalances, por qué, cómo y para qué. Aleatorización. Diseño de controles experimentales apropiados.

Clase tutorial: Presentación del trabajo de medio termino. Formación de los grupos y presentación del trabajo.

Bibliografía: Reichardt, C. S. (2019). Quasi-experimentation: A guide to design and analysis. Guilford Publications (chap. 4).

Semana 4

Clase magistral: Repaso de inferencia estadística

Temas: Repaso de test de hipótesis. Diferencias de dos medias. Errores de tipo I y tipo II. El p-valor en profundidad. ¿Qué dice y qué no dice el p-valor? El concepto de potencia estadística y su importancia en la determinación del tamaño de muestra. Diferencias de medias en muestra pareadas y su efecto en la potencia estadística. Repaso del concepto de intervalo de confianza.

Clase tutorial: Inferencia estadística. Resolución del TP2 (Repaso de inferencia estadística). Consultas sobre el desarrollo del trabajo de medio término.

Bibliografía: Lakens, D. (2022). Sample size justification. Collabra: Psychology, 8(1), 33267. Diez, D. M., Barr, C. D., & Cetinkaya-Rundel, M. (2012). OpenIntro statistics (pp. 174-175). Boston, MA, USA:: OpenIntro. (Chaps. 11-15) Goodman, S. (2008, July). A dirty dozen: twelve p-value misconceptions. In Seminars in hematology (Vol. 45, No. 3, pp. 135-140). WB Saunders. Semana 5

Clase magistral: El modelo lineal.

Temas: Definición de un modelo lineal. Estudio de sus supuestos y la "gravedad" de violarlos. Extensión a múltiples predictores. Efectos de interacción y su interpretación. Inferencia sobre los parámetros del modelo y su efecto conjunto. Interpretación de todos los tests estadísticos "usuales" como variaciones del modelo lineal.

Clase tutorial: El modelo lineal y sus aplicaciones. Resolución del TP3 (Modelo lineal). Consultas sobre el desarrollo del trabajo de medio término.

Bibliografía: Diez, D. M., Barr, C. D., & Cetinkaya-Rundel, M. (2012). OpenIntro statistics (pp. 174-175). Boston, MA, USA:: OpenIntro. (Chaps. 7-10)

Angrist, J. D., & Pischke, J. S. (2009). Mostly harmless econometrics: An empiricist's companion (Chap. 3). Princeton University Press.

https://lindeloev.github.io/tests-as-linear/ Semana 6

Clase magistral: El modelo lineal generalizado.

Temas: Extensión del modelo lineal a transformaciones de los predictores. La link function. Ejemplos de aplicación de logit, probit y Poisson. Regresión logística y sus aplicaciones en las ciencias del comportamiento. Inferencia en GLM

Clase tutorial: Avances del trabajo de medio término. Presentación de avances del trabajo de medio término.

Bibliografía: Fox, J. (2015). Applied regression analysis and generalized linear models. Sage Publications. (Part V). Semana 7

Clase magistral: El modelo lineal de efectos mixtos.

Temas: Presentación del concepto de efecto aleatorio. Ordenada al origen y pendiente aleatoria. Estudio de los supuestos de los modelos de efectos mixtos. Ejemplos de aplicación en las ciencias del comportamiento. Las ventajas sobre la potencia estadística de los diseños de medidas repetidas. Ajuste y visualización de modelos. Extensión a modelos generalizados (GLMM).

Clase tutorial: El modelo lineal de efectos mixtos. Resolución del TP3 (Modelo lineal de efectos mixtos). Consultas finales sobre el desarrollo del trabajo de medio término.

Bibliografía: Fox, J. (2015). Applied regression analysis and generalized linear models. Sage Publications. (Part VI).

Semana 8

Clase magistral: Repaso de temas de diseño experimental.

Temas: Repaso de los conceptos presentados en la primera mitad de la materia. Ejemplos de aplicación de los mismos y discusión abierta con los estudiantes.

Clase tutorial: Trabajo de medio término. Presentación por grupos del trabajo de medio término.

Bibliografía: (Esta clase no tiene bibliografía específica ya que es una clase de repaso).

Unidad 3: Diseño cuasi experimental

Semana 9 Clase magistral: Introducción al diseño cuasi experimental.

Temas: Causa y efecto. Amenazas a la validez de los diseños experiemntales (el por qué se llaman diseños cuasi experimentales). Moverse de los diseños randomizados hacia alternativas cuando no es posible la randomización.

Bibliografía: Reichardt, C. S. (2019). Quasi-experimentation: A guide to design and analysis. Guilford Publications (chap. 1 to 3). Clase tutorial: Presentación del trabajo final En esta clase se formarán los grupos y se presetarán las pautas para el desarrollo del trabajo final (diseño cuasi experimental basado en datos abiertos).

Semana 10 Clase magistral: Diseños cuasi experimentales simples

Temas: Diseños One-Group Posttest-Only y Pretest--Posttest. Ejemplos de cada tipo de diseño. Comentarios sobre validez y variaciones de los posibles diseños.

Bibliografía: Reichardt, C. S. (2019). Quasi-experimentation: A guide to design and analysis. Guilford Publications (chap. 5 and 6). Clase tutorial: Avances con el trabajo final En esta clase los estudiantes deberán decidir qué datos utilizar y una pregunta inicial (que se puede ir modificando a lo largo de los tutoriales).

Semana 11 Clase magistral: Diseños con grupos no equivalentes

Temas: Diseños básicos con grupos no equivalentes. Medidas de propensión y sesgos. Variables instrumentales. Selección de modelos. Modelos alternativos de grupos no equivalentes.

Bibliografía: Reichardt, C. S. (2019). Quasi-experimentation: A guide to design and analysis. Guilford Publications (chap. 7). Clase tutorial: Avances con el trabajo final En esta clase se espera que los estudiantes comiencen a pensar en el diseño a partir del cuál van a llevar adelante su experimento.

Semana 12 Clase magistral: Regresión discontinua

Temas: Modelos básicos de regresión discontinua. Regresión difusa. Modelos suplementados de regresión discontinua. Modelos de regresión discontinua de cluster.

Bibliografía: Reichardt, C. S. (2019). Quasi-experimentation: A guide to design and analysis. Guilford Publications (chap. 8). Clase tutorial: Avances con el trabajo final En esta clase se espera que los estudiantes comiencen a a trabajar con los datos seleccionados.

Semana 13 Clase magistral: Series de tiempo interrumpidas.

Temas: Versiones simples de los diseños de series de tiempo interrumpidas. Regresión a la media. Dieferencias en diferencias.

Bibliografía: Reichardt, C. S. (2019). Quasi-experimentation: A guide to design and analysis. Guilford Publications (chap. 9). Clase tutorial: Avances con el trabajo final En esta clase se espera que los estudiantes finalicen el análisis de su experimento y discutan las conclusiones e implicancias del mismo.

Unidad 4: Aplicaciones y reflexiones

Semana 14

Clase magistral: Meta análisis y la necesidad del consenso científico.

Temas: Modelos de meta análisis y meta análisis mixtos. Ejemplos de la bibliografía científica. La importancia del consenso científico.

Bibliografía: Herzog, M. H., Francis, G., & Clarke, A. (2019). Understanding statistics and experimental design: how to not lie with statistics (chap. 9-12). Springer Nature. Clase tutorial: Defensa del trabajo final. La modalidad de defensa del trabajo final será la de un falso congreso en el que los estudiantes deberan presentar los resultados de sus cuasi experimentos en formato de poster.

Semana 15

Clase magistral: Crisis de replicación y Ciencia Abierta

Temas: La crisis de replicación fue un evento significativo en la ciencia en general y en la psicología experimental en particular. A partir de una serie de artículos que la describieron y enunciaron se comenzaron una serie de cambios para generar una ciencia más transparente y, sobre todo, confiable. En este contexto aparece la la Ciencia Abierta.

Bibliografía: Ioannidis, J. P. (2005). Why most published research findings are false. PLoS medicine, 2(8), e124.

Nosek, B. A., Spies, J. R., & Motyl, M. (2012). Scientific utopia: II. Restructuring incentives and practices to promote truth over publishability. Perspectives on Psychological Science, 7(6), 615-631. https://doi.org/10.1177%2F1745691612459058

Foster, E. D., & Deardorff, A. (2017). Open science framework (OSF). Journal of the Medical Library Association: JMLA, 105(2), 203.

Clase tutorial: Repaso previo al segundo examen parcial.
